from pathlib import Path
import json
import os

from dotenv import load_dotenv
from serpapi import GoogleSearch


PROJECT_ROOT = Path(__file__).resolve().parents[2]

load_dotenv(PROJECT_ROOT / ".env")

OUTPUT_DIR = PROJECT_ROOT / "output" / "search_results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

QUERY_FILE = (
    PROJECT_ROOT
    / "output"
    / "search_results"
    / "final_search_query.json"
)


def load_final_query():
    """
    Load the query generated by the pipeline from final_search_query.json.
    """
    if not QUERY_FILE.exists():
        raise FileNotFoundError(
            f"Final search query not found:\n{QUERY_FILE}"
        )

    with open(QUERY_FILE, "r", encoding="utf-8") as file:
        data = json.load(file)

    query = data.get("final_query")

    if not query:
        raise ValueError("final_query is missing.")

    return query


def search_google_products(query):
    """
    Search Google Shopping for a product.
    """
    api_key = os.getenv("SERPAPI_KEY")

    if not api_key:
        raise ValueError("SERPAPI_KEY is missing from .env")

    if not query:
        raise ValueError("Product search query is required")

    print("\nSearching Google Products...")
    print(f"Query: {query}")

    params = {
        "engine": "google_shopping",
        "q": query,
        "api_key": api_key,
    }

    search = GoogleSearch(params)
    results = search.get_dict()

    return results


def save_results(results):
    """
    Save Google Shopping results.
    """
    output_path = OUTPUT_DIR / "google_products.json"

    with open(output_path, "w", encoding="utf-8") as file:
        json.dump(
            results,
            file,
            indent=4,
            ensure_ascii=False
        )

    print("\nResults saved:")
    print(output_path)


def main():
    print("\n" + "=" * 55)
    print("GOOGLE PRODUCT SEARCH")
    print("=" * 55)

    query = load_final_query()

    print(
        f"\nUsing pipeline query:\n"
        f"{query}"
    )

    results = search_google_products(query)

    save_results(results)

    shopping_results = results.get(
        "shopping_results",
        []
    )

    print("\n" + "=" * 55)
    print("SEARCH COMPLETE")
    print("=" * 55)

    print(
        f"\nProducts found: "
        f"{len(shopping_results)}"
    )

    for index, product in enumerate(
        shopping_results[:5],
        start=1
    ):
        print(f"\n{index}. {product.get('title')}")
        print(f"   Source: {product.get('source')}")
        print(f"   Price: {product.get('price')}")


if __name__ == "__main__":
    main()